# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy Library

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and build packages
        run: |
          npm ci
          npm run test:unit

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and build packages
        run: |
          npm ci
          npm run build

      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: package-artifact
          path: './dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Download archived artifact
        uses: actions/download-artifact@v3
        with:
          name: package-artifact
          path: ./dist

      - name: Publish Github private package
        working-directory: ./
        run: npm publish --no-git-checks -access restricted --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
